### ISSUE TITLE
Use Cortana to select two table spheres for command

### ISSUE THREAD

**Issue by 0x932b** [NYU-hololens/Hololens-visual#12]
## Story
**As a** Developer
**I need** to use cortana to select two tables
**So that** I can compare it

## Assumptions:
Cortana can take multiple objects

## Acceptance Criteria:
```
Given two tables
When I voice prompt
Then both of them can be selected(need some difference in the outlook as well)
```

**Comment by krishnakeshab** [comment]
Issue with debugging voice, showing common columns on mouse click...

**Comment by 0x932b** [comment]
This is done in one of kirshna's new patches
