### ISSUE TITLE
Drag with two hands on two objects

### ISSUE THREAD

**Issue by 0x932b** [NYU-hololens/Hololens-visual#14]
## Story
**As a**
**I need** 
**So that** 

## Acceptance Criteria:
```
Given
When
Then 
```

**Comment by quintoben** [comment]
Search from internet, the result is that the real HoloLens can automatically detect two hands

**Comment by quintoben** [comment]
This one needs to be tested in the real hololens

**Comment by 0x932b** [comment]
We should test this on Monday in class

**Comment by 0x932b** [comment]
After testing in todays class the hololens is not really capable of doing this.
@quintoben do you still have the search link to how to do that?
otherwise we'll work around this

**Comment by quintoben** [comment]
@u932b no....there is no much about using two hands. because i saw in the hololens emulator's tool, we can enable or disable detect right or left hand. so i indicate hololens can detect two hand at the same time.

**Comment by 0x932b** [comment]
@quintoben ok, we will use #12 cortana to be the prompt to perform operations then. You might want to look into that, something like can I call "table1 and "table2" in one voice command?

**Comment by 0x932b** [comment]
since it is not possible to use two hands, going to close the ticket for now

**Comment by quintoben** [comment]
@u932b ok
