### ISSUE TITLE
Create two CSV tables with differentiating columns in AzureSQL

### ISSUE THREAD

**Issue by 0x932b** [NYU-hololens/Hololens-visual#20]
## Story
**As a** developer
**I need** two tables with differentiating columns accessible through the hololens emulator
**So that** we can work on comparing them

## Acceptance Criteria:
```
Given an azure sql table 
When I load the scene in the hololens emulator
Then the azure sql table is accessible through unity objects
```

**Comment by 0x932b** [comment]
Can you provide the link and access?

**Comment by sonallamba** [comment]
@u932b sent you the details on slack
what link do you want?

**Comment by 0x932b** [comment]
Just the db name would do, just for records keeping on the issue

**Comment by sonallamba** [comment]
Completed..tables created from csv files

**Comment by 0x932b** [comment]
Is it still attached with http://serverholo.database.windows.net? The site seemed down right now

**Comment by sonallamba** [comment]
Yes..it is attached to it

**Comment by sonallamba** [comment]
Try to connecting to it now

**Comment by sonallamba** [comment]
Sql procedures written and added to the backend Db branch
