### ISSUE TITLE
In hololens, still can not see the panel

### ISSUE THREAD

**Issue by quintoben** [NYU-hololens/Hololens-visual#31]
## Story
**As a** 
**I need** 
**So that** 

## Acceptance Criteria:
```
Given the hololens emulator 
When the hololens start
Then the user should be able to see the UI panel
```

**Comment by 0x932b** [comment]
Canvas rendermode has to be changed to world space.
TODO:
If I fix canvas to camera, I cannot gaze on it, is there a way I can fix and gaze?
Shade the button when I gaze at it.
