### ISSUE TITLE
display columns as attributes in the table sphere

### ISSUE THREAD

**Issue by 0x932b** [NYU-hololens/Hololens-visual#4]
## Story
**As a** User 
**I need** to see the visualize of the columns in the table
**So that** I can use it for my judgement

## Assumptions:
columns defined by Time, String, number types

## Acceptance Criteria:
```
Given a table(sphere)
When I look at it
Then I can see small spheres(?)  in the big table sphere
```

**Comment by 0x932b** [comment]
TableName, columns, row count

**Comment by 0x932b** [comment]
@krishnakeshab  
there are two future steps I am seeing:
1. find a way to create the columns dynamically
2. put the generated columns within the sphere boundary
right?

**Comment by krishnakeshab** [comment]
1st part is complete. For second, may not be able to confine them within the spheres when the number is large.

**Comment by 0x932b** [comment]
ok.
for the 1 part I was thinking about the read from db or csv part, to read the columns from the csv or db backend and display them in the table
but that can be done after #46 or #45
what do you think about the second part? do we change the table in to a rectangle shape that can change dynamcially with the number of columns in it?

**Comment by krishnakeshab** [comment]
Displaying column attributes in a sphere will be difficult, specially in the case where there are more number of columns. Instead showing two groups of columns for each table.

**Comment by krishnakeshab** [comment]
That way, when we "merge" the tables, we can add another group of common columns
