### ISSUE TITLE
Import CSV files as unity resource

### ISSUE THREAD

**Issue by 0x932b** [NYU-hololens/Hololens-visual#46]
## Story
**As a** develper 
**I need** to be able to read the csv file as resource
**So that** I can visualize it directly in the hololens 

## Assumptions:
csv is readable
## Acceptance Criteria:
```
Given a csv file
When start()
Then it is read into the app
```

**Comment by 0x932b** [comment]
the current solution found is that csv files can be put into the Asset/Resource/ folder, then it can be packated within the built and deployed to the hololens app and read through a csvReader script

**Comment by krishnakeshab** [comment]
I can do this part..

**Comment by 0x932b** [comment]
i am working on it, half way through

**Comment by krishnakeshab** [comment]
Ok
